apiVersion: v1
kind: Service
metadata:
  name: my-notepad-service
  namespace: my-notepad
  labels:
    app: my-notepad
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 5000
      protocol: TCP
  selector:
    app: my-notepad